### ISSUE TITLE
Element not visibility before sm-0 and md-0

### ISSUE THREAD

**Issue by aaMY1** [devlint/gridlex#32]
For example:
`<div class="col-1_xs-12_sm-0_md-9_lg-12">...</div>`

It seems this div must be displayed on xs, md and lg sizes, and be hidden on sm.
But it's not working, cause on xs-screen div inherits "display: none" by sm-size.

Is it a bug and how to fix it? Thanks.

**Comment by ixrock** [comment]
It's bad way to mix 2 different css-entities in that manner (size of column and visibility).
With current implementation it seems not possible to turn back visibility of column, because on xs-size all previous breakpoints have been applied their styles. With changing column size `col-(1-12)` it works cause it simply overrides `flex-basis`, but `(xs|sm|md|lg)-0` uses `display:none` to hide the column.

**Solution**: make api to show/hide columns with separated modifiers `xs-visible md-hidden` and override with media-query same css-property (display).

**Comment by aaMY1** [comment]
fine, thank you!

**Comment by bryanwillis** [comment]
/************************
    HIDING COLS
*************************/
```css
[class*="-equalHeight"] > [class*="cell-"] {
  display: flex;
}

[class*="cell-"][class*="-1"], [class*="cell-"][class*="-2"], [class*="cell-"][class*="-3"], [class*="cell-"][class*="-4"], [class*="cell-"][class*="-5"], [class*="cell-"][class*="-6"], [class*="cell-"][class*="-7"], [class*="cell-"][class*="-8"], [class*="cell-"][class*="-9"], [class*="cell-"][class*="-10"], [class*="cell-"][class*="-11"], [class*="cell-"][class*="-12"] {
  display: block;
}

[class*="cell-"][class*="-0"] {
  display: none;
}

@media screen and (min-width: 320px) {
  [class*="cell-"][class*="_xs-1"], [class*="cell-"][class*="_xs-2"], [class*="cell-"][class*="_xs-3"], [class*="cell-"][class*="_xs-4"], [class*="cell-"][class*="_xs-5"], [class*="cell-"][class*="_xs-6"], [class*="cell-"][class*="_xs-7"], [class*="cell-"][class*="_xs-8"], [class*="cell-"][class*="_xs-9"], [class*="cell-"][class*="_xs-10"], [class*="cell-"][class*="_xs-11"], [class*="cell-"][class*="_xs-12"] {
    display: block;
  }

  [class*="cell-"][class*="_xs-0"] {
    display: none;
  }
}
@media screen and (min-width: 480px) {
  [class*="cell-"][class*="_sm-1"], [class*="cell-"][class*="_sm-2"], [class*="cell-"][class*="_sm-3"], [class*="cell-"][class*="_sm-4"], [class*="cell-"][class*="_sm-5"], [class*="cell-"][class*="_sm-6"], [class*="cell-"][class*="_sm-7"], [class*="cell-"][class*="_sm-8"], [class*="cell-"][class*="_sm-9"], [class*="cell-"][class*="_sm-10"], [class*="cell-"][class*="_sm-11"], [class*="cell-"][class*="_sm-12"] {
    display: block;
  }

  [class*="cell-"][class*="_sm-0"] {
    display: none;
  }
}
@media screen and (min-width: 768px) {
  [class*="cell-"][class*="_md-1"], [class*="cell-"][class*="_md-2"], [class*="cell-"][class*="_md-3"], [class*="cell-"][class*="_md-4"], [class*="cell-"][class*="_md-5"], [class*="cell-"][class*="_md-6"], [class*="cell-"][class*="_md-7"], [class*="cell-"][class*="_md-8"], [class*="cell-"][class*="_md-9"], [class*="cell-"][class*="_md-10"], [class*="cell-"][class*="_md-11"], [class*="cell-"][class*="_md-12"] {
    display: block;
  }

  [class*="cell-"][class*="_md-0"] {
    display: none;
  }
}
@media screen and (min-width: 992px) {
  [class*="cell-"][class*="_lg-1"], [class*="cell-"][class*="_lg-2"], [class*="cell-"][class*="_lg-3"], [class*="cell-"][class*="_lg-4"], [class*="cell-"][class*="_lg-5"], [class*="cell-"][class*="_lg-6"], [class*="cell-"][class*="_lg-7"], [class*="cell-"][class*="_lg-8"], [class*="cell-"][class*="_lg-9"], [class*="cell-"][class*="_lg-10"], [class*="cell-"][class*="_lg-11"], [class*="cell-"][class*="_lg-12"] {
    display: block;
  }

  [class*="cell-"][class*="_lg-0"] {
    display: none;
  }
}
@media screen and (min-width: 1200px) {
  [class*="cell-"][class*="_xl-1"], [class*="cell-"][class*="_xl-2"], [class*="cell-"][class*="_xl-3"], [class*="cell-"][class*="_xl-4"], [class*="cell-"][class*="_xl-5"], [class*="cell-"][class*="_xl-6"], [class*="cell-"][class*="_xl-7"], [class*="cell-"][class*="_xl-8"], [class*="cell-"][class*="_xl-9"], [class*="cell-"][class*="_xl-10"], [class*="cell-"][class*="_xl-11"], [class*="cell-"][class*="_xl-12"] {
    display: block;
  }

  [class*="cell-"][class*="_xl-0"] {
    display: none;
  }
```

**Comment by bryanwillis** [comment]
[Here's](https://gist.github.com/bryanwillis/1ca6b2a98908c2dcf88017a9bf19c2ef) the complete scss and css. A note though, if you use this gist, I changed the media queries to be mobile first like most other grid frameworks and dropped `.equalHeight` because I've found it has too many issues currently.

**Comment by ixrock** [comment]
Probably this should make it cleaner :D

```
@media #{$gl-xl}{
  [class*="#{$gl-colName}-"]:not([class*="_xl-0"])  {
    display: block;
  }
  [class*="#{$gl-colName}-"][class*="_xl-0"]{
    display: none;
  }
}
```
And so on..

**Comment by bryanwillis** [comment]
@ixrock Could you give an example of where it could break? 

If I'm understanding what you're saying couldn't we just add in the grid as well? 

```scss
@media #{$gl-xl}{
  [class*="#{$gl-colName}-"]:not([class*="_xl-0"])  {
    display: block;
  }
  [class*="grid"][class*="#{$gl-colName}-"]:not([class*="_xl-0"])  {
    display: flex;
  }
  [class*="#{$gl-colName}-"][class*="_xl-0"]{
    display: none;
  }
}
```

**Comment by ixrock** [comment]
@bryanwillis yeah, probably it should work!

**Comment by bryanwillis** [comment]
Here it is compiled into css with the current Gridlex variables applied. I haven't tested, but I think I got it right:  

```css
  [class*="col-"]:not([class*="col-0"]) {
    display: block;
  }

  [class*="grid-"][class*="col-"]:not([class*="col-0"]) {
    display: flex;
  }

  [class*="col-"][class*="col-0"] {
    display: none;
  }

@media screen and (max-width: 80em) {
  [class*="col-"]:not([class*="_lg-0"]) {
    display: block;
  }

  [class*="grid-"][class*="col-"]:not([class*="_lg-0"]) {
    display: flex;
  }

  [class*="col-"][class*="_lg-0"] {
    display: none;
  }
}
@media screen and (max-width: 64em) {
  [class*="col-"]:not([class*="_md-0"]) {
    display: block;
  }

  [class*="grid-"][class*="col-"]:not([class*="_md-0"]) {
    display: flex;
  }

  [class*="col-"][class*="_md-0"] {
    display: none;
  }
}
@media screen and (max-width: 48em) {
  [class*="col-"]:not([class*="_sm-0"]) {
    display: block;
  }

  [class*="grid-"][class*="col-"]:not([class*="_sm-0"]) {
    display: flex;
  }

  [class*="col-"][class*="_sm-0"] {
    display: none;
  }
}
@media screen and (max-width: 35.5em) {
  [class*="col-"]:not([class*="_xs-0"]) {
    display: block;
  }

  [class*="grid-"][class*="col-"]:not([class*="_xs-0"]) {
    display: flex;
  }

  [class*="col-"][class*="_xs-0"] {
    display: none;
  }
}
```

**Comment by bryanwillis** [comment]
**Scss** 

```scss
$breakpoints : (
  lg: 80em,
  md: 64em,
  sm: 48em,
  xs: 35.5em
) !default;

[class*="col-"]:not([class*="col-0"]) {
  display: block;
}
[class*="grid-"][class*="col-"]:not([class*="col-0"]) {
  display: flex;
}
[class*="col-"][class*="col-0"] {
  display: none;
}
@mixin make-space($breakpoints) {
  @each $breakpoint-name, $breakpoint-value in $breakpoints {
    @media screen and (max-width: $breakpoint-value) {
      [class*="#{$gl-colName}-"]:not([class*="_#{$breakpoint-name}-0"]) {
        display: block;
      }
      [class*="#{$gl-gridName}-"][class*="#{$gl-colName}-"]:not([class*="_#{$breakpoint-name}-0"])  {
        display: flex;
      }
      [class*="#{$gl-colName}-"][class*="_#{$breakpoint-name}-0"]{
        display: none;
      }
    }
  }
}
@include make-space($breakpoints);
```
