### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by David-Carty** [devlint/gridlex#86]
Issues raised have not been acknowledged for almost a year.  Grid seems a winner otherwise.

**Comment by TheKidCoder** [comment]
I'm more than happy to throw my hat in the ring as a maintainer if needed. I still use this project in quite a few projects - personal & commercial.

**Comment by TheKidCoder** [comment]
I believe it's still maintained. There is still commit activity and for the most part this is mostly a "finished" project. I'm sure @devlint would enjoy more community involvement to triage issues.

More than happy to help close out issues/triage issues if needed.

**Comment by devlint** [comment]
Hello @David-Carty & @TheKidCoder !
The project can be maintained if I see new features or bugfixes I can do.
But help is welcome because it takes time that I've not today... 

Thank you for your message, I appreciate very much!

**Comment by jepotter1-archive** [comment]
Hello @devlint, is the project still maintained in 2020? I want to use it in a CSS framework I'm developing, and I'm not sure whether I should just download it from NPM or maintain it myself as part of the framework.

If this project is abandoned, I'd be willing to step up as the new maintainer.

**Comment by jepotter1-archive** [comment]
It seems like @ChazUK has an actively maintined fork at https://github.com/ChazUK/grid. Do you have any plans to incorporate those changes upstream, or should I just use Charlie's fork?

**Comment by ChazUK** [comment]
@jwinnie 

Hi, I was looking at updating the default to become mobile first, but it's actually possible with the current repo.
I used the Bootstrap Breakpoints as they are pretty standard, and changed the Media Query to `min-width`.

```scss
$gl-gutter: 1rem;
$gl-mq-list: (
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px,
  xxl: 1440px,
);
$ql-mq-width: 'min-width';
```

I also added a few override changes to make the grid auto center.

```scss
[class~='grid'],
[class*='grid-'],
[class*='grid_'] {
  width: 100%;
  margin-left: auto;
  margin-right: auto;
  padding-left: ($gl-gutter / 2);
  padding-right: ($gl-gutter / 2);

  @each $breakpoint, $width in $gl-mq-list {
    @media (min-width: $width) {
      max-width: $width;
    }
  }
}

[class*='grid-'][class*='-noGutter'] {
  margin-left: auto;
  margin-right: auto;
  padding-left: $gl-gutter;
  padding-right: $gl-gutter;
}
```

What extra features are you looking for?
